/**
 * Maritime Sea Lane Routing Engine
 *
 * Primary path: looks up pre-computed realistic maritime routes from
 * /maritime_routes.json (generated by scripts/generate_maritime_routes.py
 * using the searoute / Marnet graph library).
 *
 * Fallback path: if the JSON is not yet loaded or a port pair is missing,
 * uses the original port-cluster gate system to keep lines over water.
 *
 * The exported maritimeRoute() function signature is unchanged -- RouteMap.tsx
 * calls it exactly as before.
 */

export type LatLon = [number, number]; // [lat, lon]

// ---------------------------------------------------------------------------
// Pre-computed route cache
// Populated once by loadMaritimeRoutes() on first call.
// ---------------------------------------------------------------------------
let routeCache: Record<string, LatLon[]> | null = null;
let loadPromise: Promise<void> | null = null;

async function loadMaritimeRoutes(): Promise<void> {
  if (routeCache !== null) return;
  if (loadPromise) return loadPromise;

  loadPromise = (async () => {
    try {
      const res = await fetch("/maritime_routes.json");
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data: Record<string, [number, number][]> = await res.json();
      routeCache = data as Record<string, LatLon[]>;
    } catch {
      // File not yet generated -- use empty cache, fallback will handle routing
      routeCache = {};
    }
  })();

  return loadPromise;
}

// Kick off the load immediately when this module is imported
loadMaritimeRoutes();

// ---------------------------------------------------------------------------
// PORT CLUSTER ASSIGNMENTS (fallback)
// ---------------------------------------------------------------------------
const PORT_CLUSTERS: Record<string, string> = {
  // Yucatan east coast ports
  "cozumel":           "yucatan-east",
  "cancun":            "yucatan-east",
  "playa del carmen":  "yucatan-east",

  // Yucatan south / Belize coast ports
  "costa maya":        "yucatan-south",
  "mahahual":          "yucatan-south",
  "belize city":       "yucatan-south",

  // Central America / Honduras
  "roatan":            "central-america",
  "honduras":          "central-america",
  "puerto cortes":     "central-america",

  // Gulf of Mexico US ports
  "galveston":         "gulf-us",
  "houston":           "gulf-us",
  "new orleans":       "gulf-us",
  "mobile":            "gulf-us",
  "tampa":             "gulf-us",
  "tampa bay":         "gulf-us",

  // US East Coast ports
  "miami":             "us-east",
  "port everglades":   "us-east",
  "fort lauderdale":   "us-east",
  "port canaveral":    "us-east",
  "jacksonville":      "us-east",
  "charleston":        "us-east",
  "savannah":          "us-east",
  "norfolk":           "us-east",
  "baltimore":         "us-east",
  "manhattan":         "us-east",
  "new york":          "us-east",
  "brooklyn":          "us-east",
  "bayonne":           "us-east",
  "cape liberty":      "us-east",
  "boston":            "us-east",

  // Bahamas
  "nassau":            "bahamas",
  "freeport":          "bahamas",
  "bimini":            "bahamas",
  "north bimini":      "bahamas",
  "celebration key":   "bahamas",
  "berry islands":     "bahamas",
  "cococay":           "bahamas",
  "great stirrup cay": "bahamas",
  "ocean cay":         "bahamas",
  "castaway cay":      "bahamas",
  "lookout cay":       "bahamas",
  "half moon cay":     "bahamas",
  "princess cays":     "bahamas",
  "royal beach club":  "bahamas",
  "turks & caicos":    "bahamas",
  "grand turk":        "bahamas",

  // Grand Cayman
  "grand cayman":      "cayman",

  // Jamaica
  "falmouth":          "jamaica",
  "ocho rios":         "jamaica",
  "kingston":          "jamaica",
  "montego bay":       "jamaica",

  // Hispaniola
  "puerto plata":      "hispaniola-north",
  "samana":            "hispaniola-east",
  "la romana":         "hispaniola-south",
  "santo domingo":     "hispaniola-south",
  "labadee":           "hispaniola-north",
  "cap-haitien":       "hispaniola-north",

  // Eastern Caribbean
  "san juan":          "eastern-caribbean",
  "st. thomas":        "eastern-caribbean",
  "st. croix":         "eastern-caribbean",
  "st. maarten":       "eastern-caribbean",
  "st. kitts":         "eastern-caribbean",
  "antigua":           "eastern-caribbean",
  "dominica":          "eastern-caribbean",
  "martinique":        "eastern-caribbean",
  "st. lucia":         "eastern-caribbean",
  "barbados":          "eastern-caribbean",
  "st. vincent":       "eastern-caribbean",
  "grenada":           "eastern-caribbean",

  // Southern Caribbean
  "aruba":             "southern-caribbean",
  "bonaire":           "southern-caribbean",
  "curacao":           "southern-caribbean",
  "cartagena":         "southern-caribbean",
  "colon":             "southern-caribbean",

  // Pacific Mexico
  "cabo san lucas":    "pacific-baja",
  "ensenada":          "pacific-baja",
  "mazatlan":          "pacific-mexico",
  "puerto vallarta":   "pacific-mexico",
  "manzanillo":        "pacific-mexico",
  "huatulco":          "pacific-mexico",

  // Alaska / Inside Passage
  "seattle":           "alaska-south",
  "vancouver":         "alaska-south",
  "victoria":          "alaska-south",
  "juneau":            "alaska-north",
  "ketchikan":         "alaska-north",
  "sitka":             "alaska-north",
  "skagway":           "alaska-north",
  "tracy arm fjord":   "alaska-north",
  "glacier bay":       "alaska-north",
  "haines":            "alaska-north",
  "wrangell":          "alaska-north",

  // Mediterranean - Western
  "barcelona":         "med-west",
  "palma de mallorca": "med-west",
  "ibiza":             "med-west",
  "valencia":          "med-west",
  "malaga":            "med-west",
  "cadiz":             "med-west",
  "lisbon":            "med-west",
  "gibraltar":         "med-west",

  // Mediterranean - Central
  "marseille":         "med-central",
  "nice":              "med-central",
  "monaco":            "med-central",
  "genoa":             "med-central",
  "la spezia":         "med-central",
  "livorno":           "med-central",
  "civitavecchia":     "med-central",
  "rome":              "med-central",
  "naples":            "med-central",
  "sardinia":          "med-central",
  "cagliari":          "med-central",
  "corsica":           "med-central",
  "ajaccio":           "med-central",
  "palermo":           "med-central",
  "catania":           "med-central",
  "messina":           "med-central",

  // Mediterranean - Adriatic
  "split":             "med-adriatic",
  "dubrovnik":         "med-adriatic",
  "venice":            "med-adriatic",
  "kotor":             "med-adriatic",

  // Mediterranean - Eastern
  "athens":            "med-east",
  "athens (piraeus)":  "med-east",
  "piraeus":           "med-east",
  "santorini":         "med-east",
  "fira":              "med-east",
  "mykonos":           "med-east",
  "rhodes":            "med-east",
  "corfu":             "med-east",
  "istanbul":          "med-east",
  "izmir":             "med-east",
  "cyprus":            "med-east",
  "limassol":          "med-east",
  "haifa":             "med-east",
  "beirut":            "med-east",
  "alexandria":        "med-east",
};

// ---------------------------------------------------------------------------
// SEA GATE DEFINITIONS (fallback)
// ---------------------------------------------------------------------------
const SEA_GATES: Record<string, LatLon[]> = {
  "yucatan-east|yucatan-south": [
    [18.5, -87.5],
  ],
  "central-america|yucatan-east": [
    [18.5, -87.5],
    [16.5, -86.0],
  ],
  "central-america|yucatan-south": [
    [16.5, -86.0],
  ],
  "gulf-us|yucatan-south": [
    [21.5, -86.8],
    [18.5, -87.5],
  ],
  "central-america|gulf-us": [
    [21.5, -86.8],
    [18.5, -87.5],
    [16.5, -86.0],
  ],
  "gulf-us|jamaica": [
    [22.5, -82.0],
  ],
  "bahamas|gulf-us": [
    [25.0, -80.5],
  ],
  "us-east|yucatan-south": [
    [24.0, -81.5],
    [21.5, -86.8],
    [18.5, -87.5],
  ],
  "central-america|us-east": [
    [24.0, -81.5],
    [18.5, -87.5],
    [16.5, -86.0],
  ],
  "jamaica|us-east": [
    [23.5, -79.5],
  ],
  "cayman|us-east": [
    [23.5, -79.5],
    [21.0, -81.5],
  ],
  "bahamas|yucatan-east": [
    [23.5, -79.5],
    [22.0, -83.0],
  ],
  "bahamas|jamaica": [
    [22.5, -77.0],
  ],
  "cayman|yucatan-east": [
    [20.0, -83.5],
  ],
  "cayman|yucatan-south": [
    [18.5, -84.5],
  ],
  "cayman|central-america": [
    [16.5, -83.5],
  ],
  "jamaica|yucatan-east": [
    [19.5, -83.0],
  ],
  "jamaica|yucatan-south": [
    [18.5, -84.5],
  ],
  "central-america|jamaica": [
    [16.5, -82.5],
  ],
  "alaska-north|alaska-south": [
    [50.5, -127.0],
    [54.5, -130.5],
  ],
};

// ---------------------------------------------------------------------------
// Fallback routing engine (gate/cluster system)
// ---------------------------------------------------------------------------
function getCluster(portName: string): string | null {
  return PORT_CLUSTERS[portName.toLowerCase()] ?? null;
}

function gateKey(a: string, b: string): string {
  return a < b ? `${a}|${b}` : `${b}|${a}`;
}

function gateFallback(
  fromName: string,
  fromCoord: LatLon,
  toName: string,
  toCoord: LatLon
): LatLon[] {
  const fromCluster = getCluster(fromName);
  const toCluster = getCluster(toName);

  if (!fromCluster || !toCluster || fromCluster === toCluster) {
    return [fromCoord, toCoord];
  }

  const key = gateKey(fromCluster, toCluster);
  const gates = SEA_GATES[key];

  if (!gates || gates.length === 0) {
    return [fromCoord, toCoord];
  }

  const reversed = fromCluster > toCluster;
  const orderedGates = reversed ? [...gates].reverse() : gates;

  return [fromCoord, ...orderedGates, toCoord];
}

// ---------------------------------------------------------------------------
// Public API -- same signature as before, RouteMap.tsx is unchanged
// ---------------------------------------------------------------------------

/**
 * Returns the full list of [lat, lon] waypoints (including start and end)
 * that keep the route over water.
 *
 * Uses pre-computed searoute/Marnet data when available.
 * Falls back to the gate/cluster system for unknown or not-yet-computed pairs.
 */
export function maritimeRoute(
  fromName: string,
  fromCoord: LatLon,
  toName: string,
  toCoord: LatLon
): LatLon[] {
  // Build the lookup key (alphabetical order, same as the Python script)
  const key = fromName < toName
    ? `${fromName}|${toName}`
    : `${toName}|${fromName}`;

  if (routeCache && routeCache[key]) {
    const waypoints = routeCache[key];
    // The JSON stores waypoints in alphabetical-key order.
    // If fromName comes after toName alphabetically, the route is stored
    // in reverse -- flip it so it runs from -> to.
    if (fromName > toName) {
      return [...waypoints].reverse() as LatLon[];
    }
    return waypoints as LatLon[];
  }

  // Cache not loaded yet or pair missing -- use gate fallback
  return gateFallback(fromName, fromCoord, toName, toCoord);
}

/**
 * Returns a Promise that resolves once the maritime routes JSON has been
 * fetched and cached. Call this before plotting routes if you want to
 * guarantee the pre-computed data is available.
 */
export async function ensureMaritimeRoutesLoaded(): Promise<void> {
  return loadMaritimeRoutes();
}
