#!/usr/bin/env python3
"""
generate_marine_forecasts.py

Fetches every unique AWIPS bulletin (Offshore Waters Forecasts and Coastal
Waters Forecasts) referenced by marine_zones.json, parses each bulletin into
its per-zone segments, and writes the result to client/public/marine_forecasts.json
keyed by zone ID.

The output structure is:
{
    "generated": "ISO8601 UTC",
    "products": {
        "OFFNT3": {"issuedAt": "...", "office": "KNHC", "synopsis": "..."},
        ...
    },
    "zones": {
        "AMZ040": {
            "productCode": "OFFNT3",
            "name": "Caribbean N of 18N W of 85W including Yucatan Basin",
            "issuedAt": "ISO8601 from header",
            "periods": [
                {"label": "TODAY", "text": "..."},
                {"label": "TONIGHT", "text": "..."},
                ...
            ],
            "raw": "<full segment text>"
        },
        ...
    }
}

This file is regenerated by the scheduled refresh (every 6 hours) and shipped
to gh-pages so the front end never has to talk to NOAA cross-origin.
"""

import json
import os
import re
import sys
import time
import urllib.request
import urllib.error
import http.client
from concurrent.futures import ThreadPoolExecutor, as_completed

HEADERS = {"User-Agent": "MyCruisingWeather/1.0 (mycruisingweather.com; contact@mycruisingweather.com)"}
PRODUCT_URL = "https://forecast.weather.gov/product.php?site=NWS&product={prod3}&issuedby={issuedby}&format=txt"
MAX_RETRIES = 4
RETRY_DELAY = 2


def http_get(url: str) -> str:
    last_err = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers=HEADERS)
            with urllib.request.urlopen(req, timeout=30) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, http.client.IncompleteRead, ConnectionResetError) as e:
            last_err = e
            if attempt < MAX_RETRIES:
                time.sleep(RETRY_DELAY * attempt)
    raise RuntimeError(f"All retries exhausted for {url}: {last_err}")


def fetch_product_text(product_code: str) -> str:
    """product_code is the full AWIPS code like 'OFFNT3' or 'CWFTBW'.
    The product.php endpoint splits it into product (first 3 chars) +
    issuedby (remaining chars).
    """
    if not product_code or len(product_code) < 4:
        return ""
    prod3 = product_code[:3]
    issuedby = product_code[3:]
    url = PRODUCT_URL.format(prod3=prod3, issuedby=issuedby)
    html = http_get(url)
    m = re.search(r"<pre[^>]*>(.+?)</pre>", html, re.S | re.I)
    if not m:
        return ""
    txt = m.group(1)
    txt = (txt.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", '"'))
    return txt.strip()


# ── Bulletin parsing ──────────────────────────────────────────────────────────
# Header pattern: NWS UGC line, e.g.
#   AMZ045-050130-
#   AMZ650-670-042000-          (short-form: 670 inherits AMZ prefix)
#   AMZ600-GMZ606-042000-       (cross-prefix)
#   AMZ650-670-042000>043000-   (occasionally with date range)
ZONE_LINE_RE = re.compile(r"^((?:[A-Z]{3}\d{3}|\d{3})(?:-(?:[A-Z]{3}\d{3}|\d{3}))*)-(\d{6}(?:>\d{6})?)-\s*$")
PERIOD_RE = re.compile(r"^\.([A-Z][A-Z0-9 /]*?)\.\.\.(.*)$")


def expand_zone_ids(raw: str) -> list[str]:
    """Expand a UGC zone-ID list, applying short-form prefix inheritance.
    Input examples:
      'AMZ650-670'        -> ['AMZ650', 'AMZ670']
      'AMZ600-GMZ606'     -> ['AMZ600', 'GMZ606']
      'AMZ650-670-AMZ672' -> ['AMZ650', 'AMZ670', 'AMZ672']
    """
    parts = raw.split("-")
    out = []
    current_prefix = ""
    for p in parts:
        if re.match(r"^[A-Z]{3}\d{3}$", p):
            current_prefix = p[:3]
            out.append(p)
        elif re.match(r"^\d{3}$", p) and current_prefix:
            out.append(current_prefix + p)
    return out


def parse_bulletin(product_code: str, text: str) -> dict:
    """Parse a marine forecast bulletin into per-zone segments.

    Returns:
      {
        "issuedAt": str,
        "office": str,
        "synopsis": str,  # global synopsis section if present
        "zones": { zoneId: {"name": str, "periods": [{label,text}], "raw": str, "issuedAt": str} }
      }
    """
    out = {"issuedAt": "", "office": "", "synopsis": "", "zones": {}}
    if not text:
        return out

    lines = text.splitlines()
    # First few lines: WMO header, AWIPS code, title, office, time
    # We look for the issuance time line ("926 AM EDT Mon May 4 2026") near the top.
    header_time_re = re.compile(r"\b(?:\d{1,4}\s+(?:AM|PM)\s+[A-Z]{2,4}\s+(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+\w+\s+\d{1,2}\s+\d{4})")
    for ln in lines[:15]:
        m = header_time_re.search(ln)
        if m:
            out["issuedAt"] = m.group(0).strip()
            break
    # Office line is typically "NWS ... <City>, <ST>" before the time
    for ln in lines[:15]:
        if ln.startswith("NWS ") or "National Hurricane Center" in ln or "National Weather Service" in ln or "Ocean Prediction Center" in ln:
            out["office"] = ln.strip()
            break

    # Walk segments. A segment starts at a ZONE_LINE and ends at "$$".
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        zm = ZONE_LINE_RE.match(line)
        if not zm:
            i += 1
            continue
        zone_ids = expand_zone_ids(zm.group(1))
        # Now read until $$.
        j = i + 1
        # Next non-blank line is the segment name; following lines may include
        # the issuance time then ".LABEL...text" period blocks.
        segment_lines = []
        seg_issued = ""
        seg_name = ""
        # Read name (first non-blank line)
        while j < n and lines[j].strip() == "":
            j += 1
        if j < n:
            seg_name = lines[j].strip().rstrip("-").strip()
            j += 1
        # Next non-blank line: try to read issued time; if not, treat as content
        while j < n and lines[j].strip() == "":
            j += 1
        if j < n and header_time_re.search(lines[j]):
            seg_issued = lines[j].strip()
            j += 1
        # Now collect content until "$$"
        content_start = j
        while j < n and lines[j].strip() != "$$":
            segment_lines.append(lines[j])
            j += 1
        raw = "\n".join(segment_lines).strip()

        # Parse periods. Period blocks span across lines until the next period
        # or end of segment. We join lines first, then split by ".LABEL..."
        joined = "\n".join(segment_lines)
        # Convert internal newlines within a period into spaces but keep period
        # boundaries; normalize by splitting on a regex that finds ".LABEL..."
        period_split = re.split(r"\n(?=\.[A-Z])", joined)
        periods = []
        for block in period_split:
            block = block.strip()
            if not block.startswith("."):
                continue
            mm = PERIOD_RE.match(block.split("\n", 1)[0])
            if not mm:
                continue
            label = mm.group(1).strip()
            first_line_text = mm.group(2).strip()
            rest = block.split("\n", 1)[1] if "\n" in block else ""
            text_combined = (first_line_text + " " + " ".join(l.strip() for l in rest.splitlines() if l.strip())).strip()
            periods.append({"label": label, "text": text_combined})

        # Special case: Synopsis segments (only one zone, label SYNOPSIS) -- store globally
        is_synopsis = False
        if periods and periods[0]["label"].upper() == "SYNOPSIS":
            is_synopsis = True
            out["synopsis"] = periods[0]["text"]

        if not is_synopsis:
            for zid in zone_ids:
                if not re.match(r"^[A-Z]{3}\d{3}$", zid):
                    continue
                out["zones"][zid] = {
                    "productCode": product_code,
                    "name": seg_name,
                    "issuedAt": seg_issued or out["issuedAt"],
                    "periods": periods,
                    "raw": raw,
                }

        i = j + 1
    return out


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    zones_path = os.path.normpath(os.path.join(script_dir, "..", "client", "public", "marine_zones.json"))
    if not os.path.exists(zones_path):
        print(f"ERROR: {zones_path} not found. Run generate_marine_zones.py first.", file=sys.stderr)
        sys.exit(2)
    zones_data = json.load(open(zones_path))

    # Collect unique product codes from zones
    products = {}
    for f in zones_data.get("features", []):
        pc = (f.get("properties") or {}).get("productCode") or ""
        if pc:
            products.setdefault(pc, 0)
            products[pc] += 1

    print(f"Fetching {len(products)} unique marine forecast products...", flush=True)

    fetched = {}
    failed = []
    with ThreadPoolExecutor(max_workers=8) as ex:
        futures = {ex.submit(fetch_product_text, pc): pc for pc in products.keys()}
        for fut in as_completed(futures):
            pc = futures[fut]
            try:
                txt = fut.result()
                if txt:
                    fetched[pc] = txt
                    print(f"  OK {pc} ({len(txt)} bytes)", flush=True)
                else:
                    failed.append(pc)
                    print(f"  EMPTY {pc}", flush=True)
            except Exception as e:
                failed.append(pc)
                print(f"  FAIL {pc}: {e}", flush=True)

    # Parse each product into zone segments
    products_meta = {}
    zones_out = {}
    for pc, txt in fetched.items():
        parsed = parse_bulletin(pc, txt)
        products_meta[pc] = {
            "issuedAt": parsed["issuedAt"],
            "office": parsed["office"],
            "synopsis": parsed["synopsis"],
            "zoneCount": len(parsed["zones"]),
        }
        for zid, seg in parsed["zones"].items():
            zones_out[zid] = seg

    # Validate coverage: every zone in marine_zones.json with productCode
    # should have a forecast segment. If not, log a warning but still write.
    missing = []
    for f in zones_data.get("features", []):
        props = f.get("properties") or {}
        zid = props.get("id") or ""
        pc = props.get("productCode") or ""
        if pc and zid and zid not in zones_out:
            missing.append((zid, pc))

    out = {
        "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "products": products_meta,
        "zones": zones_out,
    }

    out_path = os.path.normpath(os.path.join(script_dir, "..", "client", "public", "marine_forecasts.json"))
    with open(out_path, "w") as fh:
        json.dump(out, fh, separators=(",", ":"))

    print("", flush=True)
    print(f"Wrote {len(zones_out)} zone forecasts to {out_path}", flush=True)
    print(f"Products fetched: {len(fetched)}/{len(products)}", flush=True)
    if failed:
        print(f"Failed products ({len(failed)}): {', '.join(failed)}", flush=True)
    if missing:
        print(f"Zones with no parsed segment ({len(missing)}): {', '.join(z+'@'+p for z,p in missing[:20])}{'...' if len(missing) > 20 else ''}", flush=True)
    print("Done.", flush=True)
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
