#!/usr/bin/env python3
"""
generate_marine_forecasts.py

Fetches every unique AWIPS bulletin (Offshore Waters Forecasts and Coastal
Waters Forecasts) referenced by marine_zones.json, parses each bulletin into
its per-zone segments, and writes the result to client/public/marine_forecasts.json
keyed by zone ID.

The output structure is:
{
    "generated": "ISO8601 UTC",
    "products": {
        "OFFNT3": {"issuedAt": "...", "office": "KNHC", "synopsis": "..."},
        ...
    },
    "zones": {
        "AMZ040": {
            "productCode": "OFFNT3",
            "name": "Caribbean N of 18N W of 85W including Yucatan Basin",
            "issuedAt": "ISO8601 from header",
            "periods": [
                {"label": "TODAY", "text": "..."},
                {"label": "TONIGHT", "text": "..."},
                ...
            ],
            "raw": "<full segment text>"
        },
        ...
    }
}

This file is regenerated by the scheduled refresh (every 6 hours) and shipped
to gh-pages so the front end never has to talk to NOAA cross-origin.
"""

import json
import os
import re
import subprocess
import sys
import tempfile
import time
import urllib.request
import urllib.error
import http.client
from concurrent.futures import ThreadPoolExecutor, as_completed

HEADERS = {"User-Agent": "MyCruisingWeather/1.0 (mycruisingweather.com; contact@mycruisingweather.com)"}
PRODUCT_URL = "https://forecast.weather.gov/product.php?site=NWS&product={prod3}&issuedby={issuedby}&format=txt"
MAX_RETRIES = 4
RETRY_DELAY = 2


def http_get(url: str) -> str:
    last_err = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers=HEADERS)
            with urllib.request.urlopen(req, timeout=30) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, http.client.IncompleteRead, ConnectionResetError) as e:
            last_err = e
            if attempt < MAX_RETRIES:
                time.sleep(RETRY_DELAY * attempt)
    raise RuntimeError(f"All retries exhausted for {url}: {last_err}")


def fetch_product_text(product_code: str) -> str:
    """product_code is the full AWIPS code like 'OFFNT3' or 'CWFTBW'.
    The product.php endpoint splits it into product (first 3 chars) +
    issuedby (remaining chars).
    """
    if not product_code or len(product_code) < 4:
        return ""
    prod3 = product_code[:3]
    issuedby = product_code[3:]
    url = PRODUCT_URL.format(prod3=prod3, issuedby=issuedby)
    html = http_get(url)
    m = re.search(r"<pre[^>]*>(.+?)</pre>", html, re.S | re.I)
    if not m:
        return ""
    txt = m.group(1)
    txt = (txt.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", '"'))
    return txt.strip()


# ── Bulletin parsing ──────────────────────────────────────────────────────────
# Header pattern: NWS UGC line, e.g.
#   AMZ045-050130-
#   AMZ650-670-042000-          (short-form: 670 inherits AMZ prefix)
#   AMZ600-GMZ606-042000-       (cross-prefix)
#   AMZ650-670-042000>043000-   (occasionally with date range)
ZONE_LINE_RE = re.compile(r"^((?:[A-Z]{3}\d{3}|\d{3})(?:-(?:[A-Z]{3}\d{3}|\d{3}))*)-(\d{6}(?:>\d{6})?)-\s*$")
PERIOD_RE = re.compile(r"^\.([A-Z][A-Z0-9 /]*?)\.\.\.(.*)$")


def expand_zone_ids(raw: str) -> list[str]:
    """Expand a UGC zone-ID list, applying short-form prefix inheritance.
    Input examples:
      'AMZ650-670'        -> ['AMZ650', 'AMZ670']
      'AMZ600-GMZ606'     -> ['AMZ600', 'GMZ606']
      'AMZ650-670-AMZ672' -> ['AMZ650', 'AMZ670', 'AMZ672']
    """
    parts = raw.split("-")
    out = []
    current_prefix = ""
    for p in parts:
        if re.match(r"^[A-Z]{3}\d{3}$", p):
            current_prefix = p[:3]
            out.append(p)
        elif re.match(r"^\d{3}$", p) and current_prefix:
            out.append(current_prefix + p)
    return out


def parse_bulletin(product_code: str, text: str) -> dict:
    """Parse a marine forecast bulletin into per-zone segments.

    Returns:
      {
        "issuedAt": str,
        "office": str,
        "synopsis": str,  # global synopsis section if present
        "zones": { zoneId: {"name": str, "periods": [{label,text}], "raw": str, "issuedAt": str} }
      }
    """
    out = {"issuedAt": "", "office": "", "synopsis": "", "zones": {}}
    if not text:
        return out

    lines = text.splitlines()
    # First few lines: WMO header, AWIPS code, title, office, time
    # We look for the issuance time line ("926 AM EDT Mon May 4 2026") near the top.
    header_time_re = re.compile(r"\b(?:\d{1,4}\s+(?:AM|PM)\s+[A-Z]{2,4}\s+(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+\w+\s+\d{1,2}\s+\d{4})")
    for ln in lines[:15]:
        m = header_time_re.search(ln)
        if m:
            out["issuedAt"] = m.group(0).strip()
            break
    # Office line is typically "NWS ... <City>, <ST>" before the time
    for ln in lines[:15]:
        if ln.startswith("NWS ") or "National Hurricane Center" in ln or "National Weather Service" in ln or "Ocean Prediction Center" in ln:
            out["office"] = ln.strip()
            break

    # Walk segments. A segment starts at a ZONE_LINE and ends at "$$".
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        zm = ZONE_LINE_RE.match(line)
        if not zm:
            i += 1
            continue
        zone_ids = expand_zone_ids(zm.group(1))
        # Now read until $$.
        j = i + 1
        # Next non-blank line is the segment name; following lines may include
        # the issuance time then ".LABEL...text" period blocks.
        segment_lines = []
        seg_issued = ""
        seg_name = ""
        # Read name (first non-blank line)
        while j < n and lines[j].strip() == "":
            j += 1
        if j < n:
            seg_name = lines[j].strip().rstrip("-").strip()
            j += 1
        # Next non-blank line: try to read issued time; if not, treat as content
        while j < n and lines[j].strip() == "":
            j += 1
        if j < n and header_time_re.search(lines[j]):
            seg_issued = lines[j].strip()
            j += 1
        # Now collect content until "$$"
        content_start = j
        while j < n and lines[j].strip() != "$$":
            segment_lines.append(lines[j])
            j += 1
        raw = "\n".join(segment_lines).strip()

        # Parse periods. Period blocks span across lines until the next period
        # or end of segment. We join lines first, then split by ".LABEL..."
        joined = "\n".join(segment_lines)
        # Convert internal newlines within a period into spaces but keep period
        # boundaries; normalize by splitting on a regex that finds ".LABEL..."
        period_split = re.split(r"\n(?=\.[A-Z])", joined)
        periods = []
        for block in period_split:
            block = block.strip()
            if not block.startswith("."):
                continue
            mm = PERIOD_RE.match(block.split("\n", 1)[0])
            if not mm:
                continue
            label = mm.group(1).strip()
            first_line_text = mm.group(2).strip()
            rest = block.split("\n", 1)[1] if "\n" in block else ""
            text_combined = (first_line_text + " " + " ".join(l.strip() for l in rest.splitlines() if l.strip())).strip()
            periods.append({"label": label, "text": text_combined})

        # Special case: Synopsis segments (only one zone, label SYNOPSIS) -- store globally
        is_synopsis = False
        if periods and periods[0]["label"].upper() == "SYNOPSIS":
            is_synopsis = True
            out["synopsis"] = periods[0]["text"]

        if not is_synopsis:
            for zid in zone_ids:
                if not re.match(r"^[A-Z]{3}\d{3}$", zid):
                    continue
                out["zones"][zid] = {
                    "productCode": product_code,
                    "name": seg_name,
                    "issuedAt": seg_issued or out["issuedAt"],
                    "periods": periods,
                    "raw": raw,
                }

        i = j + 1
    return out


# ── HSF AT2 (Atlantic High Seas Forecast) parser ─────────────────────────────
# HSF AT2 does not segment by zone IDs. It is a free-form forecast covering the
# entire Atlantic 7N-31N west of 35W with weather features described inside
# lat/lon polygons. We extract the issuance time and slice the body into
# logical periods (Warnings, Synopsis, 24/48 hour, Forecaster).

HSF_HEADER_TIME_RE = re.compile(r"\b(\d{4}\s+UTC\s+(?:MON|TUE|WED|THU|FRI|SAT|SUN)\s+\w+\s+\d{1,2}\s+\d{4})\b")


def parse_hsf_header(txt: str) -> str:
    if not txt:
        return ""
    for ln in txt.splitlines()[:15]:
        m = HSF_HEADER_TIME_RE.search(ln)
        if m:
            return m.group(1).strip()
    return ""


def parse_hsf_periods(txt: str) -> list:
    """Slice HSF AT2 into labeled period blocks for popup display.
    Sections are delimited by lines like '.WARNINGS.', '.SYNOPSIS AND FORECAST.',
    '.FORECASTER NAME.', and the body uses '.LABEL...' or '.LABEL.' markers.
    We return a structured period list: SUMMARY, WARNINGS, SYNOPSIS, plus the
    body content split into reasonable chunks.
    """
    if not txt:
        return []
    lines = txt.splitlines()
    periods = []
    # SUMMARY block: lines 0-12 (header + area description)
    summary_lines = []
    for ln in lines[:14]:
        s = ln.strip()
        if s and not s.startswith("FZNT") and not re.match(r"^\d+$", s):
            summary_lines.append(s)
    if summary_lines:
        periods.append({"label": "AREA", "text": " ".join(summary_lines)})
    # Walk body for .SECTION. headers and group their content
    body = "\n".join(lines)
    # Split on top-level section markers like .WARNINGS. or .SYNOPSIS AND FORECAST.
    section_re = re.compile(r"^\.([A-Z][A-Z0-9 /]*?)\.\s*$", re.M)
    matches = list(section_re.finditer(body))
    for i, m in enumerate(matches):
        label = m.group(1).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        block = body[start:end]
        # Stop at the closing $$ marker if present
        if "$$" in block:
            block = block.split("$$", 1)[0]
        # Collapse whitespace and split into sentences/items
        clean = re.sub(r"\s+", " ", block).strip()
        if clean and not clean.startswith("FORECASTER"):
            # Break long blocks into period sub-items by leading ".LABEL" markers
            sub = re.split(r"\s\.([A-Z][A-Z0-9 /]*?)\s", " " + clean)
            if len(sub) > 1:
                # sub = ['', 'LABEL1', 'text1', 'LABEL2', 'text2', ...]
                # Prepend the section label to the first item
                pre = sub[0].strip()
                if pre:
                    periods.append({"label": label, "text": pre})
                for k in range(1, len(sub) - 1, 2):
                    sub_label = sub[k].strip()
                    sub_text = sub[k + 1].strip()
                    if sub_text:
                        periods.append({"label": sub_label, "text": sub_text})
            else:
                periods.append({"label": label, "text": clean})
    return periods


# ── Bahamas Department of Meteorology marine forecast ───────────────────────
# Scrapes met.gov.bs homepage for the latest marine forecast PDF link, downloads
# the PDF, extracts text via pdftotext (poppler-utils, pre-installed in sandbox
# and available in CI runner image used by the refresh workflow), and parses
# the four region sections.

BDM_HOMEPAGE = "https://met.gov.bs/"
BDM_PDF_LINK_RE = re.compile(r'href="(https?://met\.gov\.bs/[^"]*MARINE-FORECAST[^"]*\.pdf)"', re.I)
BDM_SECTION_HEADERS = {
    "NORTHERN BAHAMAS": "NORTHERN",
    "NORTHWEST BAHAMAS": "NORTHWEST",
    "CENTRAL BAHAMAS": "CENTRAL",
    "SOUTHEAST BAHAMAS": "SOUTHEAST",
}
# Map NWS marine zone ID to the BDM section that best covers it
BDM_ZONE_TO_SECTION = {
    "AMZ073": "NORTHERN",      # Atlantic from 27N to 31N between 77W and 75W (Abacos area)
    "AMZ074": "NORTHERN",
    "AMZ075": "NORTHWEST",     # New Providence / Andros / Berry Islands area
    "AMZ076": "NORTHWEST",
    "AMZ078": "NORTHWEST",
    "AMZ080": "CENTRAL",        # Central Bahamas including Cay Sal Bank
    "AMZ082": "CENTRAL",
    "AMZ083": "CENTRAL",
    "AMZ085": "SOUTHEAST",      # SE Bahamas / Inagua / Acklins / Mayaguana
    "AMZ087": "SOUTHEAST",
}


BDM_LABELS = ["ADVISORY", "WINDS", "LOCAL SEAS", "GULF STREAM", "SWELLS", "WEATHER"]
BDM_LABEL_COL = 16  # labels live in columns 0..15, values from column 16+


def _parse_bdm_section(section_text: str) -> list:
    """Parse a single BDM region section using two-column PDF layout.

    The PDF lays out each region as a two-column table: labels (ADVISORY:,
    WINDS:, etc.) are in a left column at indent 0; the value paragraph is in
    a right column at indent ~16. pdftotext -layout renders this row-by-row,
    so the value lines BRACKET the label line (a label appears at the visual
    vertical center of its value cell).

    Algorithm:
      1. Classify every non-blank line by indent: LABEL (indent < 16 and
         matches known label keyword) or VALUE (indent >= 16) or HEADER
         (anything else like region sub-header).
      2. Walk lines collecting VALUE lines into bins keyed by the LABEL whose
         influence range that line falls in. The influence range of label N
         starts halfway between label N-1 and label N, and ends halfway
         between label N and label N+1.
      3. Some labels carry an inline value on the same line (e.g. "LOCAL SEAS:
         3 - 5 feet ..."); that text is added to the label's bin.
      4. Skip empty bins and "NONE." placeholders.
    """
    lines = section_text.splitlines()
    # Build (line_index, kind, payload) records
    records = []  # (idx, kind, label_or_text, inline_value)
    label_pat = re.compile(r"^(ADVISORY|WINDS|LOCAL SEAS|GULF STREAM|SWELLS|WEATHER):\s*(.*)$")
    for i, raw in enumerate(lines):
        if not raw.strip():
            continue
        rstripped = raw.rstrip()
        indent = len(rstripped) - len(rstripped.lstrip(" "))
        text = rstripped.strip()
        if indent < 16:
            m = label_pat.match(text)
            if m:
                records.append((i, "L", m.group(1), m.group(2).strip()))
            # else: ignore HEADER / sub-header lines
        else:
            records.append((i, "V", text, ""))

    # Find label positions (line indexes of labels) and assign value lines to
    # the nearest label by line proximity, splitting ties forward.
    label_records = [r for r in records if r[1] == "L"]
    value_records = [r for r in records if r[1] == "V"]
    if not label_records:
        return []
    label_lines = [r[0] for r in label_records]
    bins = {idx: [] for idx, _, _, _ in label_records}
    # Add inline values to their label's bin first
    for idx, _, _lbl, inline in label_records:
        if inline:
            bins[idx].append(inline)
    # For each value line, find the nearest label by absolute line distance
    for vidx, _, vtext, _ in value_records:
        # Compute distance to each label
        nearest = min(label_lines, key=lambda li: (abs(vidx - li), li))
        bins[nearest].append(vtext)

    periods = []
    for idx, _, lbl, _inline in label_records:
        parts = bins.get(idx, [])
        val = re.sub(r"\s+", " ", " ".join(parts)).strip()
        val = val.lstrip(":").strip()
        if not val or val.upper() in ("NONE.", "NONE"):
            continue
        periods.append({"label": f"BAHAMAS MET / {lbl}", "text": val})
    return periods


def fetch_bdm_marine_forecast() -> dict:
    """Fetch latest BDM marine forecast PDF and parse into structured sections."""
    # Use a browser User-Agent because met.gov.bs WAF blocks generic UAs
    bdm_headers = {"User-Agent": "Mozilla/5.0 (compatible; MyCruisingWeather/1.0)"}
    req = urllib.request.Request(BDM_HOMEPAGE, headers=bdm_headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        html = resp.read().decode("utf-8", errors="replace")
    matches = BDM_PDF_LINK_RE.findall(html)
    if not matches:
        return {}
    pdf_url = matches[0]
    req = urllib.request.Request(pdf_url, headers=bdm_headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        pdf_bytes = resp.read()
    if not pdf_bytes or len(pdf_bytes) < 1000:
        return {}
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(pdf_bytes)
        tmp_path = tmp.name
    try:
        result = subprocess.run(
            ["pdftotext", "-layout", tmp_path, "-"],
            capture_output=True, text=True, timeout=20
        )
        text = result.stdout
    finally:
        os.unlink(tmp_path)
    if not text:
        return {}
    # Extract issuance time. Filename pattern: 6AM-BAHAMAS-MARINE-FORECAST-MONDAY-4TH-MAY-2026-SWH.pdf
    fn = pdf_url.rsplit("/", 1)[-1]
    m = re.match(r"(\d+)([AP]M)-BAHAMAS-MARINE-FORECAST-(\w+)-(\w+)-(\w+)-(\d{4})", fn, re.I)
    issued = ""
    if m:
        issued = f"{m.group(1)} {m.group(2).upper()} {m.group(3).title()} {m.group(4)} {m.group(5).title()} {m.group(6)}"
    # Extract synopsis: text between "GENERAL" and first region header
    syn_m = re.search(r"GENERAL.*?SITUATION:?(.*?)NORTHERN BAHAMAS", text, re.S | re.I)
    synopsis = ""
    if syn_m:
        synopsis = re.sub(r"\s+", " ", syn_m.group(1)).strip()[:800]
    # Split text into region sections by header lines
    sections = {}
    region_anchors = ["NORTHERN BAHAMAS", "NORTHWEST BAHAMAS", "CENTRAL BAHAMAS", "SOUTHEAST BAHAMAS"]
    end_anchors = region_anchors + ["MOONSET", "FORECASTER", "BAHMET"]
    for header_text, section_key in BDM_SECTION_HEADERS.items():
        # Capture from header up to the next region header (or end markers)
        end_pat = "|".join(re.escape(a) for a in end_anchors if a != header_text)
        pat = rf"{re.escape(header_text)}\s*\n(.*?)(?=\n\s*(?:{end_pat})\b|\Z)"
        sec_m = re.search(pat, text, re.S | re.I)
        if not sec_m:
            continue
        body = sec_m.group(1)
        periods = _parse_bdm_section(body)
        if periods:
            sections[section_key] = {"periods": periods, "raw": body.strip()}
    return {"issuedAt": issued, "synopsis": synopsis, "sections": sections, "sourceUrl": pdf_url}


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    zones_path = os.path.normpath(os.path.join(script_dir, "..", "client", "public", "marine_zones.json"))
    if not os.path.exists(zones_path):
        print(f"ERROR: {zones_path} not found. Run generate_marine_zones.py first.", file=sys.stderr)
        sys.exit(2)
    zones_data = json.load(open(zones_path))

    # Collect unique product codes from zones
    products = {}
    for f in zones_data.get("features", []):
        pc = (f.get("properties") or {}).get("productCode") or ""
        if pc:
            products.setdefault(pc, 0)
            products[pc] += 1

    print(f"Fetching {len(products)} unique marine forecast products...", flush=True)

    fetched = {}
    failed = []
    with ThreadPoolExecutor(max_workers=8) as ex:
        futures = {ex.submit(fetch_product_text, pc): pc for pc in products.keys()}
        for fut in as_completed(futures):
            pc = futures[fut]
            try:
                txt = fut.result()
                if txt:
                    fetched[pc] = txt
                    print(f"  OK {pc} ({len(txt)} bytes)", flush=True)
                else:
                    failed.append(pc)
                    print(f"  EMPTY {pc}", flush=True)
            except Exception as e:
                failed.append(pc)
                print(f"  FAIL {pc}: {e}", flush=True)

    # Parse each product into zone segments
    products_meta = {}
    zones_out = {}
    for pc, txt in fetched.items():
        if pc == "HSFAT2":
            # HSFAT2 is a broadcast High Seas Forecast covering the entire Atlantic
            # 7N-31N west of 35W. It does NOT segment by zone IDs; it describes
            # weather features within lat/lon polygons. Fan its full content out
            # to every zone using HSFAT2 as productCode.
            target_zones = [
                f.get("properties", {}).get("id")
                for f in zones_data.get("features", [])
                if (f.get("properties") or {}).get("productCode") == "HSFAT2"
            ]
            target_zones = [z for z in target_zones if z]
            issued = parse_hsf_header(txt)
            seg_periods = parse_hsf_periods(txt)
            products_meta[pc] = {
                "issuedAt": issued,
                "office": "NWS National Hurricane Center Miami FL",
                "synopsis": "Atlantic High Seas Forecast covering 7N-31N west of 35W including Caribbean Sea and Gulf of America.",
                "zoneCount": len(target_zones),
            }
            for zid in target_zones:
                zones_out[zid] = {
                    "productCode": "HSFAT2",
                    "name": "Atlantic High Seas Forecast (covers this zone)",
                    "issuedAt": issued,
                    "periods": seg_periods,
                    "raw": txt,
                }
            continue
        parsed = parse_bulletin(pc, txt)
        products_meta[pc] = {
            "issuedAt": parsed["issuedAt"],
            "office": parsed["office"],
            "synopsis": parsed["synopsis"],
            "zoneCount": len(parsed["zones"]),
        }
        for zid, seg in parsed["zones"].items():
            zones_out[zid] = seg

    # Bahamas Department of Meteorology supplementary forecast for Bahamas zones
    try:
        bdm = fetch_bdm_marine_forecast()
        if bdm and bdm.get("sections"):
            for zid, section_key in BDM_ZONE_TO_SECTION.items():
                section = bdm["sections"].get(section_key)
                if not section:
                    continue
                # If we already have an HSFAT2 entry for this zone, append BDM
                # as additional periods labeled "BAHAMAS MET ...". If no entry,
                # create a fresh one.
                if zid in zones_out:
                    zones_out[zid]["periods"] = list(zones_out[zid].get("periods", [])) + section["periods"]
                    zones_out[zid]["bahamasMet"] = {"issuedAt": bdm["issuedAt"], "section": section_key}
                else:
                    zones_out[zid] = {
                        "productCode": "BDM",
                        "name": f"Bahamas Department of Meteorology - {section_key}",
                        "issuedAt": bdm["issuedAt"],
                        "periods": section["periods"],
                        "raw": section.get("raw", ""),
                        "bahamasMet": {"issuedAt": bdm["issuedAt"], "section": section_key},
                    }
            products_meta["BDM"] = {
                "issuedAt": bdm["issuedAt"],
                "office": "Bahamas Department of Meteorology",
                "synopsis": bdm.get("synopsis", ""),
                "zoneCount": sum(1 for z in zones_out.values() if z.get("bahamasMet")),
            }
            print(f"  OK BDM ({bdm['issuedAt']})", flush=True)
        else:
            print("  WARN BDM: no marine forecast extracted", flush=True)
    except Exception as e:
        print(f"  FAIL BDM: {e}", flush=True)

    # Validate coverage: every zone in marine_zones.json with productCode
    # should have a forecast segment. If not, log a warning but still write.
    missing = []
    for f in zones_data.get("features", []):
        props = f.get("properties") or {}
        zid = props.get("id") or ""
        pc = props.get("productCode") or ""
        if pc and zid and zid not in zones_out:
            missing.append((zid, pc))

    out = {
        "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "products": products_meta,
        "zones": zones_out,
    }

    out_path = os.path.normpath(os.path.join(script_dir, "..", "client", "public", "marine_forecasts.json"))
    with open(out_path, "w") as fh:
        json.dump(out, fh, separators=(",", ":"))

    print("", flush=True)
    print(f"Wrote {len(zones_out)} zone forecasts to {out_path}", flush=True)
    print(f"Products fetched: {len(fetched)}/{len(products)}", flush=True)
    if failed:
        print(f"Failed products ({len(failed)}): {', '.join(failed)}", flush=True)
    if missing:
        print(f"Zones with no parsed segment ({len(missing)}): {', '.join(z+'@'+p for z,p in missing[:20])}{'...' if len(missing) > 20 else ''}", flush=True)
    print("Done.", flush=True)
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
